import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { ThemeProvider } from './context/ThemeContext';
import Navbar from './components/Navbar';
import "./globals.css";
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script type="module" src="https://unpkg.com/@splinetool/viewer@1.9.75/build/spline-viewer.js" />
      </head>
      <body className={`${inter.className} antialiased`} suppressHydrationWarning>
        <ThemeProvider>
          <Navbar />
          <main className="pt-16">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
